### ISSUE TITLE
Add a credit count feature

### ISSUE THREAD

**Issue by adismort14** [supercoww/iitbh-cgpa#11]
The current system does not automatically count the student's enrolled credits in various course types such as Institute Core, Professional Core Courses etc. All the students are required to finish a certain number of credits in each of these course types in order to graduate.

Thus, adding such a feature would actually enable the student to make more informed decisions while selecting these courses.

**Comment by tusharbansal22** [comment]
@adismort14 would you like to contribute to this issue?

**Comment by adismort14** [comment]
Yep, sure. Please assign me this issue.
