### ISSUE TITLE
Adapt Changes for the CGPA Calculation of PG Students

### ISSUE THREAD

**Issue by cocoiit** [supercoww/iitbh-cgpa#8]
Hi Team,

As the current version works only for BTech students, Can you please incorporate changes for the PG students as well? You can refer to the students handbook for the course structure and in case of any confusion, you can contact me.

Thanks.

**Comment by tusharbansal22** [comment]
The two issues the extension is facing here is
- The grade is no longer a single grade more like of format "A A A A"
- Same course runs over different semesters

**Comment by tusharbansal22** [comment]
#9  fixes the first part, the second part remains to be fixed

**Comment by aishikanandi** [comment]
Dear team, please check #10 for the same! I have considered both the issues.

**Comment by tusharbansal22** [comment]
Issue resolved in #10 .
